spring.application.name=spring-jms
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=rabbit
spring.rabbitmq.virtual-host=/
# spring.amqp.deserialization.trust.all=true
