version: '3.9'

services:
  db_gptmn:
    image: postgis/postgis:15-3.4-alpine
    container_name: postgresql_mydb
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - pg-network
    volumes:
      - postgres_mydb:/data/mydb

  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/data/pgadmin
    depends_on:
      - db_gptmn

networks:
  pg-network:
    driver: bridge

volumes:
  postgres_mydb:
  pgadmin_data: