version: "3"
services:

  # https://docs.confluent.io/platform/current/installation/configuration/broker-configs.html

  controller-1:
    image: confluentinc/cp-kafka:7.6.1
    hostname: controller-1
    container_name: controller-1
    environment:
      KAFKA_PROCESS_ROLES: "controller"
      KAFKA_NODE_ID: 1
      # На каком сокете слушает:
      KAFKA_LISTENERS: "CONTROLLER://controller-1:29092"
      # Участники кворума при определении лидера:
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:29092"
      # По какому префиксу искать первого слушателя при KRaft:
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

  broker-1:
    image: confluentinc/cp-kafka:7.6.1
    hostname: broker-1
    container_name: broker-1
    ports:
      - "9092:9092"       # Внутренний порт для общения между сервисами внутри Docker
      - "9093:29093"      # Изменено: Внешний порт 9093 хоста -> 29093 контейнера
      - "9101:9101"       # JMX
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: "broker"
      # Префикс слушателя у контроллера:
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      # Префикс слушателя для внутреннего общения брокеров:
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      # Слушатели: broker-1 слушает на 29093 для внешнего соединения
      KAFKA_LISTENERS: "PLAINTEXT://broker-1:9092,PLAINTEXT_HOST://0.0.0.0:29093"
      # Пары префикс слушателя - протокол безопасности:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      # Изменено: Адрес, по которому внешние клиенты будут подключаться с хоста
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker-1:9092,PLAINTEXT_HOST://localhost:9093"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-1:29092"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      # Фактор репликации для служебных топиков (поскольку у нас 1 брокер, ставим 1)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # JMX настройки
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

  # https://docs.confluent.io/platform/current/schema-registry/installation/config.html

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    hostname: schema-registry
    container_name: schema-registry
    ports:
      - "8081:8081"
    depends_on:
      - broker-1
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      # Подключение к брокеру по внутреннему адресу в Docker сети (не меняется)
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker-1:9092
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 1

  # https://docs.kafka-ui.provectus.io/configuration/configuration-file

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:master
    ports:
      - 8088:8080
    depends_on:
      - schema-registry
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      # Подключение к брокеру по внутреннему адресу в Docker сети (не меняется)
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: PLAINTEXT://broker-1:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      DYNAMIC_CONFIG_ENABLED: 'true'

  # Kafka REST Proxy
  kafka-rest:
    image: confluentinc/cp-kafka-rest:7.6.1
    container_name: kafka-rest
    hostname: kafka-rest
    ports:
      - "8082:8082"
    depends_on:
      - broker-1
      - schema-registry
    environment:
      # Подключение к брокерам Kafka по внутреннему адресу в Docker сети (не меняется)
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://broker-1:9092
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      # Подключение к Schema Registry
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      # Включаем отладку
      KAFKA_REST_DEBUG: 'true'