version: '3.9'

services:
  postgres:
    image: postgis/postgis:15-3.4-alpine
    environment:
      POSTGRES_DB: otus-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"