version: '3.9'

services:
  postgres:
    image: postgis/postgis:15-3.4-alpine
    container_name: postgres-15
    environment:
      POSTGRES_DB: otus-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - db-network

  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - db-network
    volumes:
      - pgadmin_data:/data/pgadmin
    depends_on:
      - postgres

networks:
  db-network:
    driver: bridge

volumes:
  pgadmin_data: